title:    "Lite App Manifests"
tagline:  "Lite Apps for Hermit: https://hermit.chimbori.com/"
url:      "https://lite-apps.chimbori.com"
cdn_url:  "https://lite-apps.chimbori.com"
exclude:  [
            # Don’t add an exclusion for *.jsx, the JSX is compiled to JS inside the _site directory.
            "*.sh",
            "babel.config.js",
            "CLA.md",
            "CNAME",
            "CONTRIBUTING.md",
            "Gemfile",
            "Gemfile.lock",
            "node_modules/",
            "package-lock.json",
            "package.json",
            "README.md"
          ]
minify_html: true
sass:
  style: compressed
